spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/mengniu_jika?useSSL=false
#    username: root
#    password: root
    url: jdbc:p6spy:mysql://rm-bp15b59z9xmng95fxwo.mysql.rds.aliyuncs.com:3306/mengniu_jika?useSSL=false
    username: mengniu
    password: Mengniu#123


#系统配置
sys:
  genFlag: true
  ocsConfig:
    host: m-k2jf16665f239814.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-k2jf16665f239814
    password: 3sKmT2cBxnVFDo9Q
  druidConfig:
    monitorUsername: root
    monitorPassword: root
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    sellernick: 蒙牛
    appkey: 32574527
    secretkey: caa79306ffa86d1f8b155e35175da724
    appName: promotioncenter-3000000037223265
    sessionkey: 50000800108d0HVToOBR15448e58ReSCHApvoPgD2jVgHrAuRcajexgrRy5oskJCrtZ