spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/adidas_20201111?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

#系统配置
sys:
  genFlag: true
  ocsConfig:
    host: m-k2j3c6d9a9b484e4.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-k2j3c6d9a9b484e4
    password: 3sKmT2cBxnVFDo9Q
  druidConfig:
    monitorUsername: root
    monitorPassword: root
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    sellernick: adidas官方旗舰店
    appkey: 31100970
    secretkey: 4243b70e27862e89a682e7118964ce5a
    appName: promotioncenter-3000000026624362
    sessionkey: 50000000825dDISrvmjRxOQb8afTFJyESrFBF1588a597jR6rtwifjLK4JUPRoyMh0f
#    sessionkey: 50000000c03tUfy12b7b69fokrPDaaGvCJp9UQlBCdSiO0VfmfMmvjsWIIaf60cXh7u