spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-k2jy9rv4f79lcq879.mysql.zhangbei.rds.aliyuncs.com:3306/xinhua_h5_test?useUnicode=true&amp;characterEncoding=utf8&amp;useServerPrepStmts=true
    username: xinhua_h5
    password: Duomai_2021


#系统配置
sys:
  genFlag: false
  ocsConfig:
    host: m-8vb570049e169b74.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-8vb570049e169b74
    password: Sov18DgdCkguHDMCjrcP
  druidConfig:
    monitorUsername: 00096098e2254fe69193da5653200bab
    monitorPassword: 0010510f513c48beaa06a6b1632e7bfd
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    sellernick: xhw
    appkey: 32086019
    secretkey: 166a2b3aa99c965e9bbb3266cf2f85ff
    appName: promotioncenter-3000000028148685
    sessionkey: 50000601a21l2b4pdLjATgPU0kIhJK4fy193f3405vHEaApraRQWTQtvaiiRVLAIzis