spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-k2j0f3w284mu8b999.mysql.zhangbei.rds.aliyuncs.com:3306/adidaszx?useUnicode=true&amp;characterEncoding=utf8&amp;useServerPrepStmts=true
    userName: adboxrds
    password: ad_2020box


#系统配置
sys:
  genFlag: false
  ocsConfig:
    host: m-k2j3c6d9a9b484e4.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-k2j3c6d9a9b484e4
    password: 3sKmT2cBxnVFDo9Q
  druidConfig:
    monitorUsername: 00096098e2254fe69193da5653200bab
    monitorPassword: 0010510f513c48beaa06a6b1632e7bfd
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    appkey: 30482173
    secretkey: d572b124d2d70b648a5e7e8790959a70
    appName: promotioncenter-3000000019832114
    sessionkey: 50000000b11gmdOAc0owgha19c51b2cl0hmTCuTgZEar8KW2EoDJnYeSwpGTQ0qoC00