spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-k2j0f3w284mu8b999.mysql.zhangbei.rds.aliyuncs.com:3306/ad_music?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useServerPrepStmts=true
    userName: adboxrds
    password: ad_2020box


#系统配置
sys:
  genFlag: false
  ocsConfig:
    host: m-k2j118ff490c3844.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-k2j118ff490c3844
    password: 3sKmT2cBxnVFDo9Q
  druidConfig:
    monitorUsername: 00096098e2254fe69193da5653200bab
    monitorPassword: 0010510f513c48beaa06a6b1632e7bfd
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    sellernick: adidas官方旗舰店
    appkey: 31100970
    secretkey: 4243b70e27862e89a682e7118964ce5a
    appName: promotioncenter-3000000026624362
    sessionkey: 50000000825dDISrvmjRxOQb8afTFJyESrFBF1588a597jR6rtwifjLK4JUPRoyMh0f
#    sessionkey: 50000000c03tUfy12b7b69fokrPDaaGvCJp9UQlBCdSiO0VfmfMmvjsWIIaf60cXh7u