spring:
  # 数据库访问配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-k2j184l5n18e89k91.mysql.zhangbei.rds.aliyuncs.com:3306/mengniu_db?useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useServerPrepStmts=true
    userName: mengniu
    password: Mengniu#db


#系统配置
sys:
  genFlag: false
  ocsConfig:
    host: m-k2j0085bc5f90f84.memcache.zhangbei.rds.aliyuncs.com
    port: 11211
    username: m-k2j0085bc5f90f84
    password: 3sKmT2cBxnVFDo9Q
  druidConfig:
    monitorUsername: 00096098e2254fe69193da5653200bab
    monitorPassword: 0010510f513c48beaa06a6b1632e7bfd
  sysConfig:
    appkey: 21699045
    secretkey: 20ee7d6400dda1c9622699123af2c2c8
  customConfig:
    sellernick: 蒙牛
    appkey: 31950443
    secretkey: 5fb1037287f6bca0f66ef6557f9f3bde
    appName: promotioncenter-3000000027083122
    sessionkey: 50000000a23Ni12iys2Oui8aIvfoPdTwg8b16e4889bbteMRtifdOmzexYn9EKq2TVt